updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status jenkinsSnapshotGit --context "$step_name"

pipelines:
  - name: create_artifactory_jenkins_plugin_snapshot
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"

    steps:
      - name: Snapshot
        type: Bash
        configuration:
          inputResources:
            - name: jenkinsSnapshotGit
          integrations:
            - name: entplus_deployer
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            # Save gradle cache
            - restore_cache_files m2_home ${HOME}/.m2
          onExecute:
            - cd $res_jenkinsSnapshotGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_BUILD_STATUS=PASS
            - export JFROG_CLI_BUILD_NAME=ecosystem-artifactory-jenkins-plugin-dev
            - export JFROG_CLI_BUILD_NUMBER=$run_number
            - export JFROG_CLI_BUILD_PROJECT=ecosys

            # Configure JFrog CLI
            - curl -fL https://getcli.jfrog.io/v2-jf | sh && chmod +x jf
            - ./jf c rm --quiet
            - ./jf c add internal --url=$int_entplus_deployer_url --user=$int_entplus_deployer_user --password=$int_entplus_deployer_apikey
            - ./jf mvnc --repo-resolve-releases ecosys-jenkins-repos --repo-resolve-snapshots ecosys-releases-snapshots --repo-deploy-snapshots ecosys-oss-snapshot-local

            # Delete former snapshots to make sure the release bundle will not contain the same artifacts
            - ./jf rt del "ecosys-oss-snapshot-local/org/jenkins-ci/plugins/artifactory/*" --quiet

            # Run install and publish
            - >
              env -i PATH=$PATH M2_HOME=$M2_HOME HOME=$HOME
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              JFROG_CLI_BUILD_PROJECT=$JFROG_CLI_BUILD_PROJECT
              ./jf mvn clean install -U -B javadoc:jar source:jar
            - ./jf rt bag && ./jf rt bce
            - ./jf rt bp
            # - ./jf bs --fail=false

            # Distribute release bundle
            - ./jf ds rbc artifactory-jenkins-plugin-snapshot $run_number --spec=./release/specs/dev-rbc-filespec.json --sign
            - ./jf ds rbd artifactory-jenkins-plugin-snapshot $run_number --site="releases.jfrog.io" --sync

          onComplete:
            - *UPDATE_COMMIT_STATUS

            # Show tests in the *Tests* tab
            - save_tests $res_jenkinsSnapshotGit_resourcePath/target/surefire-reports/

            # Save .m2 cache
            - add_cache_files ${HOME}/.m2 m2_home
